In [8]:
"""
Question 1: 2D Spiral Array
Find the pattern and complete the function:
int[][] spiral(int n);
where n is the size of the 2D array.
Sample Result
input = 3
123
894
765

input = 4
01 02 03 04
12 13 14 05
11 16 15 06
10 09 08 07

input = 8
1 2 3 4 5 6 7 8
28 29 30 31 32 33 34 9
27 48 49 50 51 52 35 10
26 47 60 61 62 53 36 11
25 46 59 64 63 54 37 12
24 45 58 57 56 55 38 13
23 44 43 42 41 40 39 14
22 21 20 19 18 17 16 15

"""
"this was my first attempt"

import numpy as np

def produce_spiral(side_length):
    #fill out from right to left until you hit a wall
    #wall = next index in the row or column bigger than the square root of the dimension of the array
    #OR
    #We hit a place that is already taken
    #when you hit a wall change directions orthogonally which means:
    #swap the row index for the column index (or vice versa)
    #increment the row index or column index
    #when there are no more elements to fill stop and return the resulting array
    #when do we change the index increment / decrement ? when we hit two walls in a row
    #In order for us to know when we hit a wall all elements should be intialized to an empty value
    """
    initialisations
    """
    spiral=np.zeros([side_length,side_length],int)
    i,j=0,0 #i for row j for column
    k=1 #index of the element to fill
    elements=range(1,side_length**2+1) #elements vector from 1 to n**2
    rowfill=True # when false we should fill the column
    increment=+1 #controls whether we should increment or dcrement the index of the row or column
    walls=0 #number of walls we hit while filling to reverse the increment
    spiral[i][j]=elements[0] #filling up the very first element makes sense
    
    while k<len(elements):
        if rowfill:
            #wall = next index in the row or column bigger than the square root of the dimension of the array
            #OR
            #We hit a place that is already taken
            if side_length > j+increment > -1 and spiral[i][j + increment]==0:
                spiral[i][j+increment]=elements[k]
                j+=increment
                k+=1
                #just for verification
                print(spiral)
            else:
                #we hit a wall
                walls+=1
                rowfill=False #switch to column fill
                if walls==2:
                    increment=-increment #reverse the index increment for the row
                    walls=0 #reinit the wall
        else: #columnfill
            if side_length > i+increment > -1 and spiral[i+increment][j]==0:
                spiral[i+increment][j] = elements[k]
                i+=increment
                k+=1
                # just for verification
                print(spiral)
            else:
                #we hit a wall
                walls+=1
                rowfill=True #switch to row fill
                if walls==2:
                    increment=-increment
                    walls=0
    return spiral

produce_spiral(3)

[[1 2 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [0 0 4]
 [0 0 0]]
[[1 2 3]
 [0 0 4]
 [0 0 5]]
[[1 2 3]
 [0 0 4]
 [0 6 5]]
[[1 2 3]
 [0 0 4]
 [7 6 5]]
[[1 2 3]
 [8 0 4]
 [7 6 5]]
[[1 2 3]
 [8 9 4]
 [7 6 5]]


array([[1, 2, 3],
       [8, 9, 4],
       [7, 6, 5]])

In [2]:
produce_spiral(8)

[[1 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 2 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 2 3 4 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 2 3 4 5 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 2 3 4 5 6 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 2 3 4 5 6 7 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 2 3 4 5 6 7 8]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [28, 29, 30, 31, 32, 33, 34,  9],
       [27, 48, 49, 50, 51, 52, 35, 10],
       [26, 47, 60, 61, 62, 53, 36, 11],
       [25, 46, 59, 64, 63, 54, 37, 12],
       [24, 45, 58, 57, 56, 55, 38, 13],
       [23, 44, 43, 42, 41, 40, 39, 14],
       [22, 21, 20, 19, 18, 17, 16, 15]])

In [9]:
def produce_spiral(side_length):
    #fill out from right to left until you hit a wall
    #wall = next index in the row or column bigger than the square root of the dimension of the array
    #OR
    #We hit a place that is already taken
    #when you hit a wall change directions orthogonally which means:
    #swap the row index for the column index (or vice versa)
    #increment the row index or column index
    #when there are no more elements to fill stop and return the resulting array
    #when do we change the index increment / decrement ? when we hit two walls in a row
    #In order for us to know when we hit a wall all elements should be intialized to an empty value
    """
    initialisations
    """
    spiral=np.zeros([side_length,side_length],int)
    i,j=0,0 #i for row j for column
    k=2 #index of the element to fill
    #elements=range(1,side_length**2+1) #elements vector from 1 to n**2
    rowfill=True # when false we should fill the column
    increment=+1 #controls whether we should increment or dcrement the index of the row or column
    walls=0 #number of walls we hit while filling to reverse the increment
    spiral[i][j]=1 #filling up the very first element makes sense
    
    while k<side_length**2+1:
        if rowfill:
            #wall = next index in the row or column bigger than the square root of the dimension of the array
            #OR
            #We hit a place that is already taken
            if side_length > j+increment > -1 and spiral[i][j + increment]==0:
                spiral[i][j+increment]=k
                j+=increment
                k+=1
                #just for verification
                print(spiral)
            else:
                #we hit a wall
                walls+=1
                rowfill=False #switch to column fill
                if walls==2:
                    increment=-increment #reverse the index increment for the row
                    walls=0 #reinit the wall
        
        else: #columnfill
            if side_length > i+increment > -1 and spiral[i+increment][j]==0:
                spiral[i+increment][j] = k
                i+=increment
                k+=1
                # just for verification
                print(spiral)
            else:
                #we hit a wall
                walls+=1
                rowfill=True #switch to row fill
                if walls==2:
                    increment=-increment
                    walls=0
    return spiral

produce_spiral(3)

[[1 2 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [0 0 4]
 [0 0 0]]
[[1 2 3]
 [0 0 4]
 [0 0 5]]
[[1 2 3]
 [0 0 4]
 [0 6 5]]
[[1 2 3]
 [0 0 4]
 [7 6 5]]
[[1 2 3]
 [8 0 4]
 [7 6 5]]
[[1 2 3]
 [8 9 4]
 [7 6 5]]


array([[1, 2, 3],
       [8, 9, 4],
       [7, 6, 5]])

In [13]:
d=np.array([[1, 2, 3],
       [8, 9, 4],
       [7, 6, 5]])
np.rot90(d)

array([[3, 4, 5],
       [2, 9, 6],
       [1, 8, 7]])

Further optimization to make use of numpy's excellent matrix manupulation library can be done. but that is for another day. 
